# Generated by Django 5.2 on 2025-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbox1_text', models.CharField(max_length=200)),
                ('textbox2_text', models.CharField(max_length=500)),
            ],
        ),
    ]
