# Generated by Django 5.2 on 2025-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person2',
        ),
        migrations.AddField(
            model_name='person',
            name='id_count',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
