# Generated by Django 5.2 on 2025-04-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_person_id_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_count',
        ),
    ]
